Start Enry server process

diff --git a/berserker-cluster b/berserker-cluster
--- a/berserker-cluster
+++ b/berserker-cluster
@@ -8,9 +8,12 @@ E_NO_SPARK=141
 
 siva="$GOPATH/bin/siva"
 siva_build_command="go get -u gopkg.in/src-d/go-siva.v1/..."
+
 jar="target/scala-2.11/berserker_2.11-0.0.2.jar"
 build_command="./sbt package"
 
+enrysrv="./enrysrv/bin/enrysrv"
+enrysrv_build_command="cd enrysrv; ./build; cd -"
 
 hash java >/dev/null 2>&1 || { echo "Please install Java" >&2; exit 1; }
 
@@ -25,6 +28,11 @@ if [[ ! -f "${siva}" ]]; then
     $siva_build_command
 fi
 
+if [[ ! -f "${enrysrv}" ]]; then
+    echo "enrysrv binary not found in ${enrysrv}. Building it using ${enrysrv_build_command}"
+    hash go >/dev/null 2>&1 || { echo "Please install Golang" >&2; exit 1; }
+    $siva_build_command
+fi
 
 
 sparkSubmit() {
@@ -45,7 +53,7 @@ sparkSubmit \
   --class tech.sourced.berserker.SparkDriver \
   --master "${MASTER:=yarn}" \
   --name "Berserker (UAST extractor)" \
-  --files "$GOPATH/bin/siva,./siva-unpack-mock" \
+  --files "$GOPATH/bin/siva,./siva-unpack-mock,./enrysrv/bin/enrysrv" \
   --packages "org.eclipse.jgit:org.eclipse.jgit:4.8.0.201706111038-r,org.rogach:scallop_2.11:3.0.3" \
   "${PWD}/${jar}" \
   "$@"
